name: Luxury Environment
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pandas
  - matplotlib
  - yfinance
  - statsmodels
  - scikit-learn
  - tensorflow
  - tabulate
  - curl_cffi
  - pip
  - pip:
      - textwrap3
